### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by Shreyas-21** [tarides/olinkcheck#61]
```[tasklist]
### Tasks
- [ ] Move tests of `Link` module to a separate file
- [ ] Use named parameters in places where the signature doesn't make it clear
- [ ] Use shorter function names
- [ ] Move data files (fixtures) under `test/` to a sub directory
- [ ] Log exceptions instead of halting the program
- [ ] Upgrade to ocaml `4.10`
```
